"""Increase institutions column length to 2000

Revision ID: 011afb6dd38f
Revises: af85a961eb0a
Create Date: 2025-03-15 04:25:58.673564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011afb6dd38f'
down_revision = 'af85a961eb0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('institutions',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('institutions',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
