"""Added courses field to User model

Revision ID: abb4d6239fce
Revises: 011afb6dd38f
Create Date: 2025-03-15 08:37:19.949333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb4d6239fce'
down_revision = '011afb6dd38f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('courses', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('courses')

    op.create_table('staff',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='staff_pkey'),
    sa.UniqueConstraint('username', name='staff_username_key')
    )
    # ### end Alembic commands ###
