"""Create users, documents, and messages tables

Revision ID: b9017535e692
Revises: d1a00375bfb7
Create Date: 2025-03-15 00:51:08.531185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9017535e692'
down_revision = 'd1a00375bfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nextTitle', sa.String(length=10), nullable=True))
        batch_op.drop_column('nesTitle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nesTitle', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('nextTitle')

    # ### end Alembic commands ###
