"""Modified nextTitle to nesTitle in User model

Revision ID: ca79837b0643
Revises: 94b0c3c5b0c6
Create Date: 2025-03-15 02:48:07.761759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca79837b0643'
down_revision = '94b0c3c5b0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nesTitle', sa.String(length=10), nullable=True))
        batch_op.drop_column('nextTitle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nextTitle', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('nesTitle')

    # ### end Alembic commands ###
