"""Add institutions column to users table

Revision ID: d1a00375bfb7
Revises: 
Create Date: 2025-03-11 15:19:42.782340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1a00375bfb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.drop_table('user_documents')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('documents_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institutions', sa.String(length=255), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('second_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('surname',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('Male', 'Female', 'Please Select'),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('applicantTitle',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('postalCode',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('matricYear',
               existing_type=mysql.YEAR(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('upgrading',
               existing_type=mysql.ENUM('YES', 'NO'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('nsfasBursary',
               existing_type=mysql.ENUM('YES', 'NO'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('school',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('nextName',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('nextsName',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('nesTitle',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('nextGender',
               existing_type=mysql.ENUM('Male', 'Female', 'Please Select'),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('nextIdNumber',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('nextEmail',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('nextAddress',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('nextPostalCode',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index('idNumber')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('password')
        batch_op.drop_column('nextsurName')
        batch_op.drop_column('selected_institutions')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('selected_institutions', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('nextsurName', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('idNumber', ['idNumber'], unique=True)
        batch_op.alter_column('nextPostalCode',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('nextAddress',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nextEmail',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('nextIdNumber',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('nextGender',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('Male', 'Female', 'Please Select'),
               existing_nullable=True)
        batch_op.alter_column('nesTitle',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('nextsName',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('nextName',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('school',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nsfasBursary',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('YES', 'NO'),
               existing_nullable=True)
        batch_op.alter_column('upgrading',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('YES', 'NO'),
               existing_nullable=True)
        batch_op.alter_column('matricYear',
               existing_type=sa.String(length=20),
               type_=mysql.YEAR(),
               existing_nullable=True)
        batch_op.alter_column('postalCode',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('applicantTitle',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('Male', 'Female', 'Please Select'),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('surname',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('second_name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('institutions')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('documents_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('user_documents',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('uploaded_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_documents_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('staff',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
