"""Added nextsurName field to User model

Revision ID: eabf9f39b117
Revises: ca79837b0643
Create Date: 2025-03-15 03:00:44.066940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabf9f39b117'
down_revision = 'ca79837b0643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nextsurName', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nextsurName')

    # ### end Alembic commands ###
